#ifndef ORDER_ENUM_H
#define ORDER_ENUM_H

enum OrderEnum
{
  /*<===== DEPLACEMENTS =====>*/
  STOP = 0,
  MOVE_LENGTHWISE = 1,
  TURN = 2,
  TURN_RIGHT_ONLY = 3,
  TURN_LEFT_ONLY = 4,
  IS_ROBOT_MOVING = 5,
  SEND_POSITION = 6,

  /*<===== INIT =====>*/
  SET_TRANSLATION_SPEED = 7,
  SET_ROTATION_SPEED = 8,
  SET_SPEEDS = 9,
  SET_X = 10,
  SET_Y = 11,
  SET_ORIENTATION = 12,
  SET_POSITION = 13,
  CREATE_HOOK = 14,
  ENABLE_HOOK = 15,
  DISABLE_HOOK = 16,

  /*<===== ASSERV =====>*/
  NO_ASSERV_TRANSLATION = 17,
  ASSERV_TRANSLATION = 18,
  NO_ASSERV_ROTATION = 19,
  ASSERV_ROTATION = 20,
  NO_ASSERV_SPEED = 21,
  ASSERV_SPEED = 22,
  DEBUG = 23,

  /*<===== MONTLHERY =====>*/
  MONTLHERY = 24,
  MOVE_FORWARD = 25,
  MOVE_BACKWARD = 26,
  TURN_RIGHT = 27,
  TURN_LEFT = 28,
  SSTOP = 29,

  /*<==== CAPTEURS =====*/
  DIST_US_BACK_RIGHT = 29,
  DIST_US_BACK_LEFT = 30,
  DIST_US_FRONT_RIGHT = 31,
  DIST_US_FRONT_LEFT = 32,
  SWITCH_US = 33,

  /*<==== CONTACTEUR ET JUMPER =====>*/
  JUMPER_STATE = 34,  //etat 0=en place , 1=retiré
  // etats contacteurs : 0=non appuyé ; 1=appuyé
  CONTACTOR1_STATE = 35,
  CONTACTOR2_STATE = 36,
  CONTACTOR3_STATE = 37,
  CONTACTOR4_STATE = 38,
  CONTACTOR5_STATE = 39,

  /*TODO ACTIONNEURS*/


};



#endif //ORDER_ENUM_H
